### ISSUE TITLE
I don't like the name :)

### ISSUE THREAD

**Issue by jpopelka** [packit/hardly#1]
I know there were options to choose from: stream-worker/packit-stream-worker/source-git-worker
but I'd personally choose `source-git-worker` because:
- we don't need `packit` in the name since it's already in `packit` namespace/org
- I prefer `source-git` over `stream`, because, as I understand it, the service will be used also for Fedora source-git, not just CenOS Stream.

WDYT @packit/the-packit-team

**Comment by lachmanfrantisek** [comment]
I don't have any strong opinion, but what Jirka wrote makes sense. So, :+1: for `source-git-worker`.

**Comment by TomasTomecek** [comment]
Agreed that source-git-worker sounds pretty boring though it's well-descriptive.

If the naming was up to me, I'd pick something absurd like `funktory`, `hard-worker` or `drummer` (can explain the names but I'll probably forget the contexts by tomorrow :D)

**Comment by lachmanfrantisek** [comment]
> If the naming was up to me, I'd pick something absurd like `funktory`, `hard-worker` or `drummer` (can explain the names but I'll probably forget the contexts by tomorrow :D)

s/hard-worker/hardly-worker

**Comment by jpopelka** [comment]
> hardly-worker

hmm, you're not the first, Tomas actually suggested that one yesterday ... and I'm not against it :)

**Comment by csomh** [comment]
`hardly` would be better :man_dancing: :exploding_head:

Seriously :smile:

**Comment by csomh** [comment]
Wait, was it only me who though that this should be called just `hardly`, no "worker" or anything like that? Apologies if this feels a never ending discussion :smile:

**Comment by jpopelka** [comment]
yes, `hardly` (no `-worker`)
@mmuzila sorry for leaving the [-worker] in the arch doc, that probably confused you

**Comment by jpopelka** [comment]
Thanks!
