### ISSUE TITLE
Add src-git MR <-> dist-git MR relation to db

### ISSUE THREAD

**Issue by jpopelka** [packit/hardly#27]

**Comment by jpopelka** [comment]
This is also needed to be able to have source-git repos and dist-git repos on a different GitService, which is the case for Fedora, where the source-git repos will (initially?) be in https://gitlab.com/fedora/src while dist-git repos remain in https://src.fedoraproject.org/rpms

**Comment by jpopelka** [comment]
Currently, we have 2 handlers
- [DistGitMRHandler](https://github.com/packit/hardly/blob/adbfb09df1031db79f16282d9b2cca0cbd44d0f0/hardly/handlers/distgit.py#L54) reacts to source-git MR and creates dist-git MR.
- [PipelineHandler](https://github.com/packit/hardly/blob/adbfb09df1031db79f16282d9b2cca0cbd44d0f0/hardly/handlers/distgit.py#L208) (name will probably change) reacts to the created dist-git MR and updates the original source-git MR. It currently knows only id of the original source-git MR as it expects that both MRs and on the same git forge, but that will change with the source-git service for Fedora.

The task here is to:
1. Design how the source-git MR <-> dist-git MR relation will be modeled in the DB. The information will be later (#44 ) used in the `PipelineHandler` as it needs to know where is the source-git MR to update.
Ideally, the new model(s) would be added to hardly only, to not touch any models in packit-service, because they don't need this. Please discuss with our DB design guru @lachmanfrantisek
2. At the end of [DistGitMRHandler.run()](https://github.com/packit/hardly/blob/adbfb09df1031db79f16282d9b2cca0cbd44d0f0/hardly/handlers/distgit.py#L54) when the new dist-git MR has been created, store the info in DB
    - [dg_mr](https://github.com/packit/hardly/blob/adbfb09df1031db79f16282d9b2cca0cbd44d0f0/hardly/handlers/distgit.py#L89) contains newly created dist-git [PullRequest](https://github.com/packit/ogr/blob/ec4f7b188d7d2113aed4b4edcbcf5102ed981be4/ogr/abstract.py#L511)
    - [mr_url](https://github.com/packit/hardly/blob/adbfb09df1031db79f16282d9b2cca0cbd44d0f0/hardly/handlers/distgit.py#L47) contains url of the original source-git MR as it was parsed as MergeRequestGitlabEvent in [Parser.parse_mr_event()](https://github.com/packit/packit-service/blob/8c754f8f0df8ccc0b21ca8173249a5ed47683211/packit_service/worker/parser.py#L202)

**Comment by lachmanfrantisek** [comment]
> 1. 

For context, [here](https://github.com/packit/research/tree/main/database) is a spike result with the plans we have for the database.
