### ISSUE TITLE
Don't add same commit comments

### ISSUE THREAD

**Issue by jpopelka** [packit/hardly#29]
I've configured [CI pipeline in our staging repo](https://gitlab.com/packit-service/rpms/open-vm-tools/-/blob/c9s/.gitlab-ci.yml) so that it behaves similarly to the CI pipeline in prod repos (dist-git).
One of the symptoms is that now we're getting (for yet unknown reason) 3 __same__ notifications to our webhook for each run:
- https://gitlab.com/packit-service/src/open-vm-tools/-/merge_requests/15 (staging repo MR)
- https://gitlab.com/redhat/centos-stream/src/luksmeta/-/merge_requests/5 (prod repo MR)

Given that the payload is really the same, we can't select just some (one) of them, but have to do some deduplication, i.e. check whether exactly the same commit comment has already been added before adding a new one.

**Comment by TomasTomecek** [comment]
hmmm, would be nice to discuss options

it would be awesome to have the info inside the database, although I'm not sure if that's an overkill

**Comment by jpopelka** [comment]
I tried now [on stg](https://gitlab.com/packit-service/src/open-vm-tools/-/merge_requests/18) and didn't see any duplicate comments or any duplicated events sent to our webhook.

In the initial description, I mention https://gitlab.com/redhat/centos-stream/src/luksmeta/-/merge_requests/5 but when I check https://gitlab.com/redhat/centos-stream/src/luksmeta/-/merge_requests/6 created 2 months later, it looks OK.
Perhaps it's been fixed meanwhile? Anyway, closing for now.

**Comment by jpopelka** [comment]
Reopening, I can see it again.
