### ISSUE TITLE
Dist-git MR's target branch to match source-git MR's target branch

### ISSUE THREAD

**Issue by csomh** [packit/hardly#36]
When hardly creates an MR in dist-git, the target branch for the MR should be the same as the target branch of the source-git MR. (Currently this is always set to default branch of the repository). Example: `rawhide` → `rawhide`.

A new configuration key in `.distro/source-git.yaml`, called `downstream_branch_name`, should be used to override this behavior (if specified), and allow explicitly setting the name of the target branch in dist-git. Example: `fedora-rawhide` → `rawhide`.

In case the target branch does not exist in dist-git, a comment informing about this should be made on the source-git MR.

**Comment by jpopelka** [comment]
> Currently this is always set to `c9s`

Do you know where is it set? I can't find it.

**Comment by csomh** [comment]
It's actually the [default branch of the dist-git repository](https://github.com/packit/packit/blob/31978201d42740419abd4ea66f39beed741f9c4d/packit/api.py#L254), which in case of gitlab.com/redhat/centos-stream is c9s. This could be customized by setting the `dist_git_branch` argument when [`sync_release` is called in *hardly*](https://github.com/packit/hardly/blob/a90498942ca386759d5585c31b5eda3b9251a97b/hardly/handlers/distgit.py#L89-L97).
