### ISSUE TITLE
Dist-git MR target branch is always rawhide

### ISSUE THREAD

**Issue by jpopelka** [packit/hardly#45]
[Fedora source-git MR with target f36 branch](https://gitlab.com/fedora/src/python-httpretty/-/merge_requests/2) is expected (?) to create a dist-git MR against `f36` branch as well, but hardly created [Fedora dist-git MR against `rawhide`](https://src.fedoraproject.org/rpms/python-httpretty/pull-request/19).

**Comment by TomasTomecek** [comment]
In future, I expect folks will want to create dist-git PRs against multiple branches.

Do I understand this issue correctly that you want to be able to specify where the downstream PR is meant to be created?

**Comment by jpopelka** [comment]
Yes

Example
I have version `1.1` in `F35` and version `2.2` in `F36` & `rawhide/main`.
I'll probably have different branches for them in source-git as well, likely called the same as in dist-git, i.e. `F35`, `F36`, `main`.

If someone finds a bug in `1.1` in `F35` and knows how to fix it, they can create an MR against source-git's `F35` branch and I expect that the bot creates a corresponding PR in dist-git's `F35`, not `rawhide/main`.

**Comment by csomh** [comment]
Isn't this a duplicate of #36? Or the other way around? :)

**Comment by jpopelka** [comment]
Oh, it is a duplicate, indeed. Closing then.
