### ISSUE TITLE
Remove 'files/docker'

### ISSUE THREAD

**Issue by csomh** [packit/hardly#7]
As the image is built by GitHub actions, I think this directory could be removed.

- [ ] `Dockerfile.worker` should be move to the root of the repo and renamed to `Containerfile`.
- [ ] `Dockerfile.tests` should be moved to the root of the repo and renamed to `Containerfile.tests`.

**Comment by jpopelka** [comment]
The "dockerfiles" are now `files/Containerfile` and `files/Containerfile.tests`.
I don't see why they need to be in the root of the repo, so closing this, reopen with justification if you think otherwise.
