### ISSUE TITLE
Use rpms/redhat-internal-test-package for stream-source-git workflow validation

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/hardly#81]
TODO:

* [x] create a source-git repo for rpms/redhat-internal-test-package
  * this will probably be tricky since the package is brutally trivial
  * Needs [PACKIT-2391](https://issues.redhat.com/browse/PACKIT-2391) first
  * You'd probably need to ask @TomasTomecek to add you to the [subgroup](https://gitlab.com/groups/redhat/centos-stream/src/-/group_members) in order to be able to create (and push to) the repo.
* [x] Make sure that opening a source-git MR
  * creates a valid dist-git MR
  * pipelines statuses are synced correctly
* [x] Document how to use this to test hardly changes

More info the SPIKE card which is linked to this one.

http://pkgs.devel.redhat.com/cgit/rpms/redhat-internal-test-package
https://gitlab.com/redhat/centos-stream/rpms/redhat-internal-test-package/-/tree/c9s

**Comment by jpopelka** [comment]
Source-git repo: https://gitlab.com/redhat/centos-stream/src/redhat-internal-test-package
MR: https://gitlab.com/redhat/centos-stream/src/redhat-internal-test-package/-/merge_requests/1
Docs: https://github.com/packit/deployment/pull/394
